apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  schemaVersion: v1.0.0
  name: terraform-aws-github-runner
  description: Forked from https://github.com/philips-labs/terraform-aws-github-runner
  annotations:
    github.com/project-slug: Bandwidth/terraform-aws-github-runner
  organization: BW
  costCenter: Development - Software Infra
  platformType: N/A
  buildPlatform: GitHub Actions
spec:
  type: Utility
  owner: github/band-swi
  lifecycle: |
    Prototype
    dependsOn:
        - resource:platform/N/A
        - resource:cost-center/Development - Software Infra
